version: '2'
services:
  mapd-00:
    image: ${MAPD_IMAGE}
    restart: always
    entrypoint: ["mapd_server", "--http-port", "9090", "-p", "9091", "--data", "/data/mapd-data-00", "--db-query-list", "/data/warm-up.sql"]
    volumes:
      - ./data:/data
  mapd-api:
    image: shusson/mapd-api:1.2.2
    restart: always
    entrypoint: ["/go/bin/app"]
    command: ["-url", "http://mapd-00:9090"]
    ports:
      - 4000:4000
    depends_on:
      - mapd-00
